name: 'bain_capital_portfolio_analytics'
version: '1.0.0'
config-version: 2

profile: 'bain_capital'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Date range for analysis
  start_date: '2020-01-01'
  end_date: '2024-12-31'
  # Default lookback periods
  default_lookback_days: 90
  ytd_lookback_days: 365

seeds:
  bain_capital_portfolio_analytics:

models:
  bain_capital_portfolio_analytics:
    # Pipeline A - Simple Cashflow Analysis
    pipeline_a:
      staging:
        +materialized: view
        +tags: ["staging", "pipeline_a"]
      intermediate:
        +materialized: view
        +tags: ["intermediate", "pipeline_a"]
      marts:
        +materialized: table
        +tags: ["marts", "pipeline_a"]

    # Pipeline B - Medium Trade Analytics
    pipeline_b:
      staging:
        +materialized: view
        +tags: ["staging", "pipeline_b"]
      intermediate:
        +materialized: view
        +tags: ["intermediate", "pipeline_b"]
      marts:
        +materialized: table
        +tags: ["marts", "pipeline_b"]

    # Pipeline C - Complex Portfolio Performance Analytics
    pipeline_c:
      staging:
        +materialized: view
        +tags: ["staging", "pipeline_c"]
      intermediate:
        +materialized: view
        +tags: ["intermediate", "pipeline_c"]
      marts:
        +materialized: table
        +tags: ["marts", "pipeline_c"]

    # Utilities: Shared macros and helper functions
    utilities:
      +materialized: view
      +tags: ["utilities"]
