# dbt profiles configuration for Snowflake
# Uses hardcoded values for Artemis runner compatibility
bain_capital:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: GWAYEQA-CEB31664
      user: AWENDELA
      password: Xarsedasdvp1!1
      database: BAIN_ANALYTICS
      warehouse: COMPUTE_WH
      schema: DEV
      threads: 4
      client_session_keep_alive: False
